### ISSUE TITLE
Player still not working on react-native-tvos @0.74

### ISSUE THREAD

**Issue by Veryyapeee** [THEOplayer/react-native-theoplayer#336]
Hi,

I'm trying to launch an example app (as well as my own app), and while trying to launch an android application, I'm getting following error

`> Task :react-native-theoplayer:compileDebugKotlin FAILED
e: file:///Users/lighthouse/Desktop/tet/ott-react-native/node_modules/react-native-theoplayer/android/src/main/java/com/theoplayer/ads/AdAdapter.kt:186:12 Object is not abstract and does not implement abstract member public abstract fun getCustomIntegration(): String? defined in com.theoplayer.android.api.ads.GoogleImaAd
e: file:///Users/lighthouse/Desktop/tet/ott-react-native/node_modules/react-native-theoplayer/android/src/main/java/com/theoplayer/ads/AdAdapter.kt:253:12 Object is not abstract and does not implement abstract member public abstract fun getCustomIntegration(): String? defined in com.theoplayer.android.api.ads.AdBreak`

**Comment by KestasVenslauskas** [comment]
@Veryyapeee they just released new SDK version that is broken.
This has nothing to do with react-native version.
Just add `THEOplayer_sdk=7.5.0` in `gradle.properties` to use older SDK version (current 7.6.0) for now.

**Comment by tvanlaerhoven** [comment]
@Veryyapeee we released a native Android player SDK that breaks the react-native-theoplayer ad interface. You can either pin the native SDK to 7.5.0, just like @KestasVenslauskas suggests, or upgrade to the latest version of react-native-theoplayer.

**Comment by tvanlaerhoven** [comment]
@Veryyapeee closing this ticket for now. Let us know if you're still experiencing issues.
